-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 10:35:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FLIGHT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FLIGHT` (
  `Number` INT NOT NULL,
  `Airline` VARCHAR(45) NULL,
  `Weekdays` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AIRPORT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AIRPORT` (
  `Airport_code` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Airport_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FLIGHT_LEG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FLIGHT_LEG` (
  `Number` INT NOT NULL,
  `Leg_no` INT NOT NULL,
  `Airport_dep_code` VARCHAR(45) NOT NULL,
  `Airport_arr_code` VARCHAR(45) NOT NULL,
  `Scheduled_dep_time` VARCHAR(45) NULL,
  `Scheduled_arr_time` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`, `Leg_no`),
  INDEX `fk_airport_flight_leg_dep_idx` (`Airport_dep_code` ASC) VISIBLE,
  INDEX `fk_airport_flight_leg_arr_idx` (`Airport_arr_code` ASC) VISIBLE,
  CONSTRAINT `fk_flight_flight_leg`
    FOREIGN KEY (`Number`)
    REFERENCES `mydb`.`FLIGHT` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airport_flight_leg_dep`
    FOREIGN KEY (`Airport_dep_code`)
    REFERENCES `mydb`.`AIRPORT` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airport_flight_leg_arr`
    FOREIGN KEY (`Airport_arr_code`)
    REFERENCES `mydb`.`AIRPORT` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AIRPLANE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AIRPLANE_TYPE` (
  `Type_name` VARCHAR(45) NOT NULL,
  `Max_seats` INT NULL,
  `Company` VARCHAR(45) NULL,
  PRIMARY KEY (`Type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AIRPLANE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AIRPLANE` (
  `Airplane_id` INT NOT NULL,
  `Total_no_of_seats` INT NULL,
  `Type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airplane_id`),
  INDEX `fk_airplane_type_airplane_idx` (`Type_name` ASC) VISIBLE,
  CONSTRAINT `fk_airplane_type_airplane`
    FOREIGN KEY (`Type_name`)
    REFERENCES `mydb`.`AIRPLANE_TYPE` (`Type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEG_INSTANCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LEG_INSTANCE` (
  `Number` INT NOT NULL,
  `Leg_no` INT NOT NULL,
  `Date` DATE NOT NULL,
  `No_of_avail_seats` INT NULL,
  `Airplane_id` INT NOT NULL,
  `Airport_dep_code` VARCHAR(45) NULL,
  `Airport_arr_code` VARCHAR(45) NULL,
  `Dep_time` VARCHAR(45) NULL,
  `Arr_time` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`, `Leg_no`, `Date`),
  INDEX `fk_airplane_leg_instance_idx` (`Airplane_id` ASC) VISIBLE,
  INDEX `fk_airport_dep_leg_instance_idx` (`Airport_dep_code` ASC) VISIBLE,
  INDEX `fk_airport_arr_leg_instance_idx` (`Airport_arr_code` ASC) VISIBLE,
  CONSTRAINT `fk_flight_leg_instance`
    FOREIGN KEY (`Number` , `Leg_no`)
    REFERENCES `mydb`.`FLIGHT_LEG` (`Number` , `Airport_dep_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airplane_leg_instance`
    FOREIGN KEY (`Airplane_id`)
    REFERENCES `mydb`.`AIRPLANE` (`Airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airport_dep_leg_instance`
    FOREIGN KEY (`Airport_dep_code`)
    REFERENCES `mydb`.`AIRPORT` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airport_arr_leg_instance`
    FOREIGN KEY (`Airport_arr_code`)
    REFERENCES `mydb`.`AIRPORT` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEAT` (
  `Number` INT NOT NULL,
  `Leg_no` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Seat_no` INT NOT NULL,
  `Customer_name` VARCHAR(45) NULL,
  `Cphone` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`, `Leg_no`, `Date`, `Seat_no`),
  CONSTRAINT `fk_leg_instance_seat`
    FOREIGN KEY (`Number` , `Leg_no` , `Date`)
    REFERENCES `mydb`.`LEG_INSTANCE` (`Number` , `Leg_no` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FARE` (
  `Number` INT NOT NULL,
  `Code` VARCHAR(45) NOT NULL,
  `Restrictions` VARCHAR(45) NULL,
  `Amount` INT NULL,
  PRIMARY KEY (`Code`, `Number`),
  INDEX `fk_flight_fare_idx` (`Number` ASC) VISIBLE,
  CONSTRAINT `fk_flight_fare`
    FOREIGN KEY (`Number`)
    REFERENCES `mydb`.`FLIGHT` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAN_LAND`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAN_LAND` (
  `Airport_code` VARCHAR(45) NULL,
  `Type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`Airport_code`, `Type_name`),
  INDEX `fk_airplane_type_can_land_idx` (`Type_name` ASC) VISIBLE,
  CONSTRAINT `fk_airport_can_land`
    FOREIGN KEY (`Airport_code`)
    REFERENCES `mydb`.`AIRPORT` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airplane_type_can_land`
    FOREIGN KEY (`Type_name`)
    REFERENCES `mydb`.`AIRPLANE_TYPE` (`Type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
